"""data models for notes"""

from sqlalchemy import Boolean, Column, ForeignKey, Integer, String, Table
from sqlalchemy.orm import declarative_base, Mapped, mapped_column

Base = declarative_base()


class NoteModel(Base):
    """Data class for notes"""

    __tablename__ = "note_base"

    # added from source
    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str]
    content: Mapped[str]
    source: Mapped[str]
    type: Mapped[str]
    # generated by AI
    topics: Mapped[str]  # an array?
    summary: Mapped[str]
    sentiment: Mapped[str]
    # index related
    indexed: Mapped[bool]
    dirty: Mapped[bool]
    index_reference: Mapped[str]

    __mapper_args__ = {
        "polymorphic_identity": "note",
        "polymorphic_on": "type",
    }

    def __repr__(self):
        return f"{self.__class__.__name__}({self.name!r})"


class VoiceNoteModel(NoteModel):
    """class for voice notes"""

    __tablename__ = "note_voicenote"

    id: Mapped[int] = mapped_column(ForeignKey("note_base.id"), primary_key=True)

    # file information
    file_location: Mapped[str]
    file_encoding: Mapped[str]
    # processing
    transcribed: Mapped[bool]
    transcription_rating: Mapped[int]
    service_used: Mapped[str]

    __mapper_args__ = {
        "polymorphic_identity": "voicenote",
    }

    def __repr__(self):
        return f"{self.__class__.__name__}({self.name!r})"
